services:
  nginx:
    container_name: nginx-server
    hostname: nginx
    image: nginx:1.27.2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    networks:
      - default
  php:
    container_name: php-fpm
    hostname: php
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    networks:
      - default
  db:
    image: postgres:17.1
    hostname: postgres_db
    environment:
      POSTGRES_DB: cookbook
      POSTGRES_USER: cookbook
      POSTGRES_PASSWORD: 12345678
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres_db:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    tty: true
#  elasticsearch:
#    hostname: elasticsearch
#    build:
#      context: ./docker/elasticsearch
#    volumes:
#      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
#    environment:
#      discovery.type: single-node
#      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
#      ELASTICSEARCH_USERNAME: kibana_system
#      ELASTIC_PASSWORD: SimplePassw
#      xpack.security.enabled: 'false'
#      xpack.license.self_generated.type: basic
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    networks:
#      - default
#  kibana:
#    hostname: "kibana"
#    image: kibana:8.11.1
#    volumes:
#      - ./docker/kibana/data:/usr/share/kibana/data
#    environment:
#      SERVER_NAME: kibana.loc
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#      ELASTICSEARCH_USERNAME: kibana_system
#      ELASTICSEARCH_PASSWORD: SimplePassw
#    ports:
#      - "5601:5601"
#    networks:
#      - default
#    depends_on:
#      - elasticsearch

networks:
  default:
    driver: bridge