openapi: 3.0.3
info:
  title: Recipe book
  version: 1.0.0

servers:
  - url: http://localhost
    description: Local server
tags:
  - name: Recipes
    description: Рецепты

paths:
  /api/v1/meals/:
    # Список блюд
    get:
      responses:
        200:
          description: Список блюд
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/meal"
    # Создание или обновление блюда
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: id блюда, если оно существует (передаётся для обновления)
                name:
                  type: string
                  description: Название блюда
                  example: Французские булочки
                slug:
                  type: string
                  description: Символьный код
                  example: francuzskie-bulochki
      responses:
        200:
          description: Успешное создание или обновление блюда
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    description: id созданного элемента

  /api/v1/meals/{id}:
    get:
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: Детальная информация о блюде
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/meal"

  /api/v1/meals/{slug}:
    get:
      parameters:
        - $ref: "#/components/parameters/slug"
      responses:
        200:
          description: Детальная информация о блюде
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/meal"

  /api/v1/meals/{id}/recipes:
    get:
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: Список рецептов блюда
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/recipe-item"

  /api/v1/meals/{slug}/recipes:
    get:
      parameters:
        - $ref: "#/components/parameters/slug"
      responses:
        200:
          description: Список рецептов блюда
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/recipe-item"

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    apiKey:
      type: apiKey
      description: API key to authorize requests.
      name: X-Authorization
      in: header

  parameters:
    id:
      name: id
      in: path
      required: true
      description: ID записи в базе данных
      schema:
        type: integer
    slug:
      name: slug
      in: path
      required: true
      description: Символьный код
      schema:
        type: string


  schemas:
    # Блюдо
    meal:
      description: Блюдо
      type: object
      properties:
        id:
          type: integer
          description: id
        name:
          type: string
          description: Название блюда
        slug:
          type: string
          description: Символьный код блюда

    # Рецепт для листинга
    recipe-item:
      description: Краткая информация о рецепте для листинга
      type: object
      properties:
        id:
          type: integer
          description: id
        name:
          type: string
          description: Название рецепта
        slug:
          type: string
          description: Символьный код блюда
        cooking_time:
          type: integer
          description: Время приготовления в секундах
        images:
          items:
            $ref: "#/components/schemas/image"

    # Изображение каталога
    image:
      description: Изображение
      type: object
      properties:
        url:
          type: string
          description: Ссылка на изображение
        width:
          type: integer
          description: Ширина изображения
        height:
          type: integer
          description: Высота изображения
        alt:
          type: string
          description: Параметр alt
